FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD ./requirements/base.txt /code/
ADD ./requirements/development.txt /code/
RUN pip install --upgrade pip
RUN pip install -r development.txt
ADD . /code/
# COPY ./wait-for-it.sh /wait-for-it.sh
# RUN chmod +x wait-for-it.sh
