version: '3'

services:

  db:
    build:
      context: ./
      dockerfile: Dockerfile-db
    command: mysqld --user=mysql --innodb-use-native-aio=0
    env_file:
      - ./env/development/.env
    volumes:
      - ./db-datadir:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    tty: true

  web:
    build:
      context: ./
      dockerfile: Dockerfile-web-dev
    command: /bin/bash -c "/wait-for-it.sh db:3306 && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./env/development/.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
