# Generated by Django 2.1.8 on 2019-05-27 12:58

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(db_column='ANSWER ID', primary_key=True, serialize=False)),
                ('answer_texts', django_mysql.models.JSONField(default=list)),
                ('additional_message', django_mysql.models.JSONField(default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(db_column='ENTITY ID', primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=50, unique=True)),
                ('entity_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='EntityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('synonyms', django_mysql.models.JSONField(default=list)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogue.Entity')),
            ],
            options={
                'db_table': 'entity_value',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(db_column='QUESTION ID', primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=100, unique=True)),
                ('intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('training_phrases', django_mysql.models.JSONField(default=list)),
                ('parent_answer_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogue.Question'),
        ),
    ]
