# Generated by Django 2.1.8 on 2019-05-29 14:53

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(db_column='ANSWER ID', primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('additional_message', django_mysql.models.JSONField(default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(db_column='ENTITY ID', primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=50, unique=True)),
                ('entity_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='EntityValue',
            fields=[
                ('entity_value_id', models.AutoField(db_column='ENTITY VALUE ID', primary_key=True, serialize=False)),
                ('value_text', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogue.Entity')),
            ],
            options={
                'db_table': 'entity_value',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('phrase_id', models.AutoField(db_column='PHRASE ID', primary_key=True, serialize=False)),
                ('phrase_text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'phrase',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(db_column='QUESTION ID', primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=100, unique=True)),
                ('intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_answer_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('synonym_id', models.AutoField(db_column='SYNONYM ID', primary_key=True, serialize=False)),
                ('synonym_text', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('entity_value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogue.EntityValue')),
            ],
            options={
                'db_table': 'synonym',
            },
        ),
        migrations.AddField(
            model_name='phrase',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogue.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogue.Question'),
        ),
    ]
