# Generated by Django 2.1.9 on 2019-06-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityvalue',
            name='entity_value_temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='entity_value_temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='synonym_temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
