# Generated by Django 2.1.9 on 2019-06-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0002_auto_20190622_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityvalue',
            old_name='entity_value_temp_id',
            new_name='value_temp_id',
        ),
        migrations.RenameField(
            model_name='synonym',
            old_name='entity_value_temp_id',
            new_name='value_temp_id',
        ),
    ]
