# Generated by Django 2.1.9 on 2019-07-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0004_auto_20190627_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='entity_type_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
