# Generated by Django 2.1.9 on 2019-07-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0007_auto_20190713_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='entity',
            new_name='entities',
        ),
    ]
