# Generated by Django 2.1.9 on 2019-07-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0009_auto_20190713_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('entities_id', models.AutoField(db_column='ENTITIES ID', primary_key=True, serialize=False)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(max_length=50, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'entities',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='entities',
        ),
        migrations.AddField(
            model_name='entities',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='dialogue.Question'),
        ),
    ]
