# Generated by Django 2.1.9 on 2019-07-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0010_auto_20190715_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='entity_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
