# Generated by Django 2.1.10 on 2019-08-26 00:41

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0012_remove_question_parent_answer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('payload_id', models.AutoField(db_column='PAYLOAD ID', primary_key=True, serialize=False)),
                ('state', models.CharField(default='none', max_length=20)),
                ('message', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payload',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='additional_message',
        ),
        migrations.RemoveField(
            model_name='question',
            name='additional_state',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='payload',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='dialogue.Question'),
        ),
    ]
