# Generated by Django 2.1.10 on 2019-08-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0013_auto_20190826_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='payload_temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
