# Generated by Django 2.1.10 on 2019-08-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0014_payload_payload_temp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='random',
            field=models.BooleanField(default=False),
        ),
    ]
